postgres:
  protocol: postgres
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: manabie
  sslmode: ""
  timeout: 0
jwt_secret: secret
max_todo: 5
http:
  port: 5050
  host: ""